In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [ ]:
# Read the data

df_BOS = pd.read_csv('BOS_12_11_10001.csv',delimiter=';') # BOS data
df_corr = pd.read_csv('cross_correction0001.csv',delimiter=';')  # correlation of crosses

In [77]:
df_BOS

,x,y,x-displacement,y-displacement,Uncertainty Vx,Uncertainty Vy
0,62.9742,16.1565,-0.041227,-0.112492,0.000915,0.000774
1,63.2925,16.1565,-0.041468,-0.112285,0.000849,0.000753
2,63.6108,16.1565,-0.041702,-0.111995,0.000960,0.000774
3,63.9291,16.1565,-0.041889,-0.111694,0.000993,0.000816
4,64.2474,16.1565,-0.042036,-0.111369,0.001018,0.000812
...,...,...,...,...,...,...
14897,63.9291,-11.2182,-0.034678,-0.107163,0.001770,0.003242
14898,64.2474,-11.2182,-0.035508,-0.108491,0.001990,0.003242
14899,64.5658,-11.2182,-0.035676,-0.108698,0.001773,0.003189
14900,63.6108,-11.5365,-0.033719,-0.105839,0.001598,0.002272
14901,63.9291,-11.5365,-0.033753,-0.106148,0.001805,0.002433

In [78]:
# get the average x displacement of the crosses

avg_x_corr = (df_corr
            #   .groupby('x-displacement')
              .agg(mean_x_corr = ('x-displacement','mean'))
)

# get the standard deviation of the x-displacement, and an average of the uncertainties on x-displacement of the crosses

std_x_corr = (df_corr
            #   .groupby('x-displacement')
              .agg(mean_x_unc = ('Uncertainty Vx','mean'),std_x_corr = ('x-displacement','std'))
              .reset_index()
)

avg_x_corr,std_x_corr

(             x-displacement
 mean_x_corr       -0.035537,
         index  Uncertainty Vx  x-displacement
 0  mean_x_unc        0.001627             NaN
 1  std_x_corr             NaN        0.004799)

In [79]:
# get the average y displacement of the crosses

avg_y_corr = (df_corr
            #   .groupby('x-displacement')
              .agg(mean_y_corr = ('y-displacement','mean'))
)

# get the standard deviation of the y-displacement, and an average of the uncertainties on y-displacement of the crosses


std_y_corr = (df_corr
            #   .groupby('x-displacement')
              .agg(mean_y_unc = ('Uncertainty Vy','mean'),std_y_corr = ('y-displacement','std'))
              .reset_index()
)

avg_y_corr, std_y_corr

(             y-displacement
 mean_y_corr       -0.109489,
         index  Uncertainty Vy  y-displacement
 0  mean_y_unc        0.001769             NaN
 1  std_y_corr             NaN        0.003463)

In [80]:
# use the correction data to correct the BOS data frame

df_BOS['x-displacement'] = df_BOS['x-displacement'] - avg_x_corr['x-displacement'][0]
df_BOS['y-displacement'] = df_BOS['y-displacement'] - avg_y_corr['y-displacement'][0]
df_BOS['Uncertainty Vx'] = np.sqrt(df_BOS['Uncertainty Vx']**2 + std_x_corr['Uncertainty Vx'][0]**2 + std_x_corr['x-displacement'][1]**2)
df_BOS['Uncertainty Vy'] = np.sqrt(df_BOS['Uncertainty Vy']**2 + std_y_corr['Uncertainty Vy'][0]**2 + std_y_corr['y-displacement'][1]**2)

C:\Users\assecchiaroli\AppData\Local\Temp\ipykernel_12684\2906677876.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_BOS['x-displacement'] = df_BOS['x-displacement'] - avg_x_corr['x-displacement'][0]
C:\Users\assecchiaroli\AppData\Local\Temp\ipykernel_12684\2906677876.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_BOS['y-displacement'] = df_BOS['y-displacement'] - avg_y_corr['y-displacement'][0]

In [81]:
# check that the data differ from the original one
# this is the finalized BOS data frame
df_BOS

,x,y,x-displacement,y-displacement,Uncertainty Vx,Uncertainty Vy
0,62.9742,16.1565,-0.005691,-0.003003,0.005149,0.003965
1,63.2925,16.1565,-0.005931,-0.002796,0.005137,0.003961
2,63.6108,16.1565,-0.006165,-0.002506,0.005157,0.003965
3,63.9291,16.1565,-0.006352,-0.002205,0.005163,0.003973
4,64.2474,16.1565,-0.006500,-0.001880,0.005168,0.003972
...,...,...,...,...,...,...
14897,63.9291,-11.2182,0.000859,0.002326,0.005367,0.005063
14898,64.2474,-11.2182,0.000028,0.000998,0.005444,0.005063
14899,64.5658,-11.2182,-0.000139,0.000791,0.005368,0.005029
14900,63.6108,-11.5365,0.001817,0.003650,0.005313,0.004504
14901,63.9291,-11.5365,0.001784,0.003341,0.005379,0.004587